# frozen_string_literal: true

require 'rspec'
require 'byebug'
require 'pry'
require 'singleton'
require_relative 'chess/bishop'
require_relative 'chess/board'
require_relative 'chess/movable'
require_relative 'chess/stepable'
require_relative 'chess/slideable'
require_relative 'chess/king'
require_relative 'chess/knight'
require_relative 'chess/null_piece'
require_relative 'chess/pawn'
require_relative 'chess/piece'
require_relative 'chess/queen'
require_relative 'chess/rook'
